spring:
  application:
    name=booking-system:

  datasource:
    url: jdbc:postgresql://localhost:5432/seat_reservation
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      probes:
        enabled: true
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true